### ISSUE TITLE
StackとFlowの情報制御

### ISSUE THREAD

**Issue by mkusaka** [team-nishio/GitTutorial#9]
## 概要
流れる情報(例えばチャット)と流れてほしくない情報(定期的に参照する情報、例えば使い方など)の管理をしたい。

## 解決策案
  + stack
     + Google Docs
     + Qiita
  + flow
     + slackで十分

**Comment by yousukensh** [comment]
Stackについてはこの前作ったGoogleの共有フォルダで一元管理することにしましょう！

普段の連絡はSlack、イシューやソースコードの管理はgithub、それ以外の情報共有はGoogleドキュメントで

**Comment by mkusaka** [comment]
了解ですー
